image: node:18

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

unit-tests:
  stage: test
  script:
    - npm run test:coverage
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      junit: junit.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)%/'

e2e-tests:
  image: mcr.microsoft.com/playwright:v1.42.1-jammy
  stage: test
  script:
    - npm ci
    - npm run build
    - npx playwright install --with-deps
    - npm run start &
    - npx wait-on http://localhost:3000
    - npm run test:e2e
  artifacts:
    when: always
    paths:
      - test-results/
      - playwright-report/
